### ISSUE TITLE
11th gen processors

### ISSUE THREAD

**Issue by expacc007** [mBilG/Hackintosh-Laptop_Xiaomi-Mi-Notebook-Pro-2020-Enhanced#1]
Does it work with 11th gen processors and iris Xe ? https://www.mi.com/in/product/mi-notebook-pro

**Comment by mBilG** [comment]
As far as I know, 11th Gen and Iris Xe are not supported  by macOS itself..
So I'm not sure if it'll work.. but it will probably involve loads of work.. which might in the end result in nothing if Apple doesn't release any 11th gen intel devices (which is highly unlikely at this point)..
